// angular-frontend/src/app/pages/bulletin-board/bulletin-board.component.ts
import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { AppStateService } from '../../services/app-state.service';

@Component({
  selector: 'app-bulletin-board',
  standalone: true,
  template: `
    <div>
      <h2 style="margin-bottom: 20px; font-size: 18px; font-weight: 600">Bảng tin học tập</h2>
      <div class="card">
        <div class="card-header">Danh sách lớp học phần đang học</div>
        <div class="card-body" style="padding: 0">
          <table class="data-table">
            <thead>
              <tr>
                <th>STT</th>
                <th>Tên môn</th>
                <th>Mã lớp</th>
                <th style="text-align:center">Tuần học</th>
                <th style="text-align:center">Trạng thái</th>
              </tr>
            </thead>
            <tbody>
              @for (course of state.courses(); track course.id; let i = $index) {
                <tr style="cursor:pointer" (click)="goToCourse(course.id)">
                  <td>{{ i + 1 }}</td>
                  <td>{{ course.name }}</td>
                  <td>{{ course.code }}</td>
                  <td style="text-align:center">{{ course.weeks }}</td>
                  <td style="text-align:center">
                    <span class="badge" [class.badge-success]="course.status==='on_track'" [class.badge-warning]="course.status==='late'" [class.badge-info]="course.status==='ontime'">
                      {{ course.status === 'on_track' ? 'Đúng tiến độ' : course.status === 'late' ? 'Chậm tiến độ' : 'Đúng hạn' }}
                    </span>
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `
})
export class BulletinBoardComponent {
  state = inject(AppStateService);
  private router = inject(Router);

  goToCourse(id: number) {
    this.router.navigate(['/dashboard/classes/learning', id]);
  }
}

// src/pages/BulletinBoard.jsx
import { useContext } from 'react'
import { useNavigate } from 'react-router-dom'
import { AppContext } from '../App'

export default function BulletinBoard() {
    const { courses } = useContext(AppContext)
    const navigate = useNavigate()

    return (
        <div>
            <div className="card">
                <div className="card-header">
                    Các lớp học phần học kỳ hiện tại (2025_2026_1)
                </div>
                <div className="card-body" style={{ padding: 0 }}>
                    <table className="data-table">
                        <thead>
                            <tr>
                                <th style={{ width: 60 }}>STT</th>
                                <th>Tên lớp học phần</th>
                                <th style={{ width: 120, textAlign: 'center' }}>Tuần học</th>
                                <th style={{ width: 120, textAlign: 'center' }}>Số buổi nghỉ</th>
                                <th style={{ width: 140, textAlign: 'center' }}>Trạng thái</th>
                            </tr>
                        </thead>
                        <tbody>
                            {courses.map((course, idx) => (
                                <tr key={course.id} style={{ cursor: 'pointer' }} onClick={() => navigate(`/dashboard/classes/learning/${course.id}`)}>
                                    <td style={{ textAlign: 'center' }}>{idx + 1}</td>
                                    <td>
                                        <a style={{ color: course.status === 'late' ? 'var(--danger)' : 'var(--primary)' }}>
                                            {course.name}-1-25 ({course.code})
                                        </a>
                                    </td>
                                    <td style={{ textAlign: 'center' }}>{course.weeks}</td>
                                    <td style={{ textAlign: 'center', color: course.status === 'late' ? 'var(--danger)' : 'inherit' }}>
                                        {course.absences}
                                    </td>
                                    <td style={{ textAlign: 'center' }}>
                                        <span className={`badge ${course.status === 'late' ? 'badge-warning' : 'badge-success'}`}>
                                            {course.status === 'late' ? 'Chậm tiến độ' : 'Đúng tiến độ'}
                                        </span>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    )
}
