// angular-frontend/src/app/pages/course-learning/course-learning.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { AppStateService } from '../../services/app-state.service';
import { ApiService } from '../../services/api.service';
import { Lesson, CourseData, UploadedFile } from '../../models/course.model';
import { MicroActivityComponent } from '../../components/micro-activity/micro-activity.component';
import { ImmersiveTextComponent } from '../../components/immersive-text/immersive-text.component';
import { MindmapViewComponent } from '../../components/mindmap-view/mindmap-view.component';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-course-learning',
  standalone: true,
  imports: [MicroActivityComponent, ImmersiveTextComponent, MindmapViewComponent],
  template: `
    <div class="learning-layout" style="margin:-24px;height:calc(100% + 48px)">
      <!-- Lesson Sidebar -->
      <div class="lesson-sidebar" [class.collapsed]="sidebarCollapsed()">
        <button class="lesson-sidebar-toggle" (click)="sidebarCollapsed.update(v=>!v)">
          {{ sidebarCollapsed() ? '»' : '«' }}
        </button>
        @if (courseData()) {
          <div class="lesson-header">{{ courseData()!.courseName }} ({{ courseData()!.courseCode }})</div>
          @for (lesson of courseData()!.lessons; track lesson.id) {
            <div class="lesson-item-wrapper">
              <div class="lesson-item" [class.active]="activeLesson() === lesson.id" (click)="toggleLesson(lesson.id)">
                <div style="width:4px;min-height:28px;border-radius:2px" [style.background]="lesson.type==='exam' ? '#f0ad4e' : 'var(--primary-light)'"></div>
                @if (lesson.type !== 'info' && lesson.type !== 'exam') {
                  <span class="lesson-toggle" [class.expanded]="activeLesson() === lesson.id">▶</span>
                }
                <span class="lesson-name">{{ lesson.name }}</span>
                @if (lesson.completed) { <span class="lesson-check">✓</span> }
              </div>
              @if (activeLesson() === lesson.id && lesson.type !== 'info' && lesson.type !== 'exam') {
                <div class="lesson-sub-items">
                  <div class="lesson-sub-item" [class.active]="activeTab()==='content'" (click)="setTab('content')">
                    <span class="sub-bullet">●</span> Nội dung bài học
                  </div>
                  <div class="lesson-sub-item" [class.active]="activeTab()==='materials'" (click)="setTab('materials')">
                    <span class="sub-bullet">●</span> Tài liệu tham khảo
                  </div>
                </div>
              }
            </div>
          }
        }
      </div>

      <!-- Content Area -->
      <div class="lesson-content-area">
        @if (!selectedLesson() || !selectedLesson()!.content) {
          <div class="content-placeholder">
            {{ !activeLesson() ? 'Vui lòng chọn 1 bài học để hiển thị nội dung.' : 'Nội dung bài học này chưa có dữ liệu demo.' }}
          </div>
        } @else if (activeTab() === 'content') {
          <div style="height:100%;display:flex;flex-direction:column">
            <!-- View Mode Toolbar -->
            <div class="view-mode-toolbar">
              @for (mode of viewModes; track mode.id) {
                <button class="view-mode-btn" [class.active]="viewMode()===mode.id" (click)="viewMode.set(mode.id)">
                  <span class="view-mode-icon">{{ mode.icon }}</span>
                  <span class="view-mode-label">{{ mode.label }}</span>
                </button>
              }
            </div>
            <div class="view-mode-content">
              @switch (viewMode()) {
                @case ('source') {
                  <!-- Source View -->
                  <div class="source-view" style="padding: 24px; overflow-y: auto; height: 100%;">
                    @if (sourceLoading()) {
                      <div class="imm-loading" style="display:flex;flex-direction:column;align-items:center;padding:40px 0;color:var(--text-secondary)">
                        <div style="font-size:32px;margin-bottom:16px;animation:pulse 1.5s infinite">📄</div>
                        <p style="margin:0;font-size:15px;font-weight:500">AI đang phân tích tài liệu để tạo cấu trúc bài học...</p>
                        <p style="margin:4px 0 0;font-size:13px;opacity:0.8">Vui lòng đợi trong giây lát</p>
                      </div>
                    } @else if (sourceError()) {
                      <div class="content-placeholder">
                        <div style="text-align:center">
                          <span style="font-size:32px;display:block;margin-bottom:16px;color:var(--text-light)">⚠️</span>
                          <h3 style="margin:0 0 8px;color:var(--text-primary)">Lỗi phân tích tài liệu</h3>
                          <p style="color:var(--text-secondary);margin:0;line-height:1.6">{{ sourceError() }}</p>
                        </div>
                      </div>
                    } @else if (sourceContent()) {
                      <h2 class="source-title" style="margin:0 0 24px;font-size:24px;color:var(--text-primary);border-bottom:1px solid var(--border);padding-bottom:16px;">{{ sourceContent()!.title }}</h2>
                      @for (sec of sourceContent()!.sections; track $index; let idx = $index) {
                        <div class="source-section" style="margin-bottom:24px">
                          <h3 class="source-heading" style="margin:0 0 12px;font-size:18px;color:#3b82f6">{{ sec.heading }}</h3>
                          @if (sec.text) {
                            @for (p of sec.text.split('\n'); track $index) {
                              <p class="source-text" style="margin:0 0 8px;line-height:1.6;color:var(--text-secondary)">{{ p }}</p>
                            }
                          }
                          @if (sec.list && sec.list.length > 0) {
                            <ul class="source-list" style="margin:0;padding-left:20px;color:var(--text-secondary);line-height:1.6">
                              @for (item of sec.list; track $index) { <li style="margin-bottom:6px">{{ item }}</li> }
                            </ul>
                          }
                        </div>
                      }
                    } @else {
                      <div class="content-placeholder">
                        <div style="text-align:center">
                          <span style="font-size:32px;display:block;margin-bottom:16px;color:var(--text-light)">📄</span>
                          <h3 style="margin:0 0 8px;color:var(--text-primary)">Chưa có dữ liệu phân tích</h3>
                          <p style="color:var(--text-secondary);margin:0;line-height:1.6">
                            Vui lòng tải lên tài liệu bài giảng (PDF/PPT) trong phần "Tài liệu tham khảo"<br>để AI có thể đọc và tạo cấu trúc bài học tại đây.
                          </p>
                        </div>
                      </div>
                    }
                  </div>
                }
                @case ('immersive') {
                  <app-immersive-text [courseId]="courseId" [lessonId]="activeLesson()!" [lesson]="selectedLesson()!" />
                }
                @case ('mindmap') {
                  <app-mindmap-view [courseId]="courseId" [lessonId]="activeLesson()!" [lesson]="selectedLesson()!" />
                }
                @case ('slides') {
                  <div class="content-placeholder">
                    <div style="text-align:center">
                      <span style="font-size:32px;display:block;margin-bottom:16px;color:var(--text-light)">▶ Slides</span>
                      <h3 style="margin:0 0 8px;color:var(--text-primary)">Slides & Narration</h3>
                      <p style="color:var(--text-secondary);margin:0;line-height:1.6">
                        Tính năng trình chiếu kèm thuyết minh AI đang được phát triển.<br>
                        Sẽ sớm ra mắt trong phiên bản tiếp theo!
                      </p>
                    </div>
                  </div>
                }
              }
            </div>
          </div>
        } @else if (activeTab() === 'materials') {
          <div style="height:100%;display:flex;flex-direction:column">
            @if (!viewingFile()) {
              <div style="padding:20px 24px 12px">
                <h3 style="margin:0 0 4px;font-size:16px;color:var(--text-primary)">Tài liệu tham khảo</h3>
                <p style="margin:0;font-size:13px;color:var(--text-secondary)">Chọn tài liệu bạn muốn xem</p>
              </div>
              @if (uploadedFiles().length === 0) {
                <div class="content-placeholder" style="flex:1">Chưa có tài liệu nào.</div>
              } @else {
                <div style="padding:0 24px 16px;display:flex;flex-direction:column;gap:8px">
                  @for (file of uploadedFiles(); track $index) {
                    <div style="display:flex;align-items:center;gap:16px;padding:16px;border-radius:12px;background:#fff;border:1px solid #e2e8f0;cursor:pointer;box-shadow:0 1px 3px rgba(0,0,0,0.05);transition:all 0.2s"
                      (click)="openFile(file)"
                      onmouseover="this.style.borderColor='#3b82f6';this.style.transform='translateY(-1px)';this.style.boxShadow='0 4px 6px -1px rgba(59, 130, 246, 0.1)'"
                      onmouseout="this.style.borderColor='#e2e8f0';this.style.transform='none';this.style.boxShadow='0 1px 3px rgba(0,0,0,0.05)'">
                      
                      <div style="width:48px;height:48px;border-radius:10px;background:#eff6ff;display:flex;align-items:center;justify-content:center;color:#3b82f6;flex-shrink:0">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                      </div>
                      
                      <div style="flex:1;min-width:0">
                        <div style="font-size:11px;font-weight:700;color:#3b82f6;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px">BÀI GIẢNG</div>
                        <div style="font-weight:600;font-size:15px;color:#1e293b;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{{ fixEncoding(file.originalName) }}</div>
                        <div style="font-size:13px;color:#64748b;margin-top:4px;display:flex;align-items:center;gap:6px">
                          <span>{{ getFileIcon(file.mimetype) }}</span>
                          <span style="width:4px;height:4px;border-radius:50%;background:#cbd5e1"></span>
                          <span>{{ formatSize(file.size) }}</span>
                        </div>
                      </div>
                      
                      <div style="width:36px;height:36px;border-radius:50%;background:#f1f5f9;display:flex;align-items:center;justify-content:center;color:#64748b;flex-shrink:0" class="file-view-btn">
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12h20"/><path d="m15 5 7 7-7 7"/></svg>
                      </div>
                    </div>
                  }
                </div>
              }
            } @else {
              <div style="flex:1;display:flex;flex-direction:column;height:100%">
                <div style="display:flex;align-items:center;justify-content:space-between;padding:10px 16px;border-bottom:1px solid var(--border);background:var(--bg-secondary);flex-shrink:0">
                  <button style="padding:6px 12px;border-radius:6px;border:1px solid var(--border);background:var(--bg-primary);color:var(--text-primary);font-size:13px;cursor:pointer;font-weight:500"
                    (click)="viewingFile.set('')">← Quay lại</button>
                </div>
                <iframe [src]="viewingFile()" style="flex:1;width:100%;border:none;background:#fff" title="Preview tài liệu"></iframe>
              </div>
            }
          </div>
        }
      </div>

      @if (activeActivity()) {
        <app-micro-activity [activity]="activeActivity()!" (closeEvent)="activeActivity.set(null)" />
      }
    </div>
  `
})
export class CourseLearningComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private state = inject(AppStateService);
  private api = inject(ApiService);
  private sanitizer = inject(DomSanitizer);

  courseId = '';
  courseData = signal<CourseData | null>(null);
  activeLesson = signal<string | null>(null);
  activeTab = signal('content');
  viewMode = signal('source');
  sidebarCollapsed = signal(false);
  activeActivity = signal<any>(null);
  uploadedFiles = signal<UploadedFile[]>([]);
  viewingFile = signal<SafeResourceUrl | string>('');

  sourceContent = signal<any>(null);
  sourceLoading = signal(false);
  sourceError = signal<string | null>(null);

  viewModes = [
    { id: 'source', icon: '⊞', label: 'Source' },
    { id: 'immersive', icon: '≡', label: 'Immersive Text' },
    { id: 'slides', icon: '▶', label: 'Slides & Narration' },
    { id: 'mindmap', icon: '◎', label: 'Mindmap' },
  ];

  ngOnInit() {
    this.courseId = this.route.snapshot.paramMap.get('courseId') || '';
    const lessons = this.state.lessons() as any;
    this.courseData.set(lessons[this.courseId] || null);
  }

  selectedLesson = (): Lesson | null => {
    const data = this.courseData();
    const id = this.activeLesson();
    if (!data || !id) return null;
    return data.lessons.find(l => l.id === id) || null;
  };

  toggleLesson(id: string) {
    this.activeLesson.set(this.activeLesson() === id ? null : id);
    this.activeTab.set('content');
    this.viewMode.set('source');
    this.viewingFile.set('');
    this.sourceContent.set(null);
    this.sourceError.set(null);
    this.fetchFiles();
    if (this.activeLesson() && this.activeLesson() !== 'info' && this.activeLesson() !== 'exam') {
      this.fetchSourceContent();
    }
  }

  fetchSourceContent() {
    this.sourceLoading.set(true);
    this.sourceError.set(null);
    const lessonId = this.activeLesson();
    if (!lessonId) return;

    this.api.getCourseSource({
      courseId: this.courseId,
      lessonId: lessonId,
      title: this.selectedLesson()?.name || `Bài ${lessonId}`
    }).subscribe({
      next: (data: any) => {
        this.sourceContent.set(data);
        this.sourceLoading.set(false);
      },
      error: (err: any) => {
        console.error(err);
        this.sourceError.set(err.error?.error || 'Lỗi khi gọi API Source');
        this.sourceLoading.set(false);
      }
    });
  }

  setTab(tab: string) {
    this.activeTab.set(tab);
    this.viewingFile.set('');
    if (tab === 'materials') this.fetchFiles();
  }

  getInteractionPoint(sectionIdx: number) {
    return this.selectedLesson()?.content?.interactionPoints?.find(p => p.sectionIdx === sectionIdx) || null;
  }

  fetchFiles() {
    const params: any = { courseId: this.courseId };
    const lesson = this.activeLesson();
    if (lesson && lesson !== 'info' && lesson !== 'exam') params.lessonId = lesson;
    this.api.getUploads(params).subscribe({
      next: (data: any) => this.uploadedFiles.set(Array.isArray(data) ? data : []),
      error: () => this.uploadedFiles.set([])
    });
  }

  openFile(file: UploadedFile) {
    this.viewingFile.set(this.getIframeUrl(file));
  }

  getIframeUrl(file: UploadedFile): SafeResourceUrl {
    const base = environment.apiUrl;
    const url = file.downloadUrl ? `${base}${file.downloadUrl}` : `${base}/uploads/${file.courseId}/${file.lessonId}/${file.storedName}`;
    return this.sanitizer.bypassSecurityTrustResourceUrl(url);
  }

  fixEncoding(text: string): string {
    try {
      // Fix ISO-8859-1 decoding issues that show up as garbled UTF-8
      return decodeURIComponent(escape(text));
    } catch {
      return text;
    }
  }

  formatSize(bytes: number) {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / 1024 / 1024).toFixed(2) + ' MB';
  }

  getFileIcon(mimetype: string) {
    if (mimetype === 'application/pdf') return 'PDF';
    if (mimetype?.includes('presentation') || mimetype?.includes('powerpoint')) return 'PPT';
    if (mimetype?.includes('word')) return 'DOC';
    return 'FILE';
  }
}

// src/pages/CourseLearning.jsx
import { useContext, useState, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import { AppContext } from '../App'
import MicroActivity from '../components/MicroActivity'
import ImmersiveText from '../components/ImmersiveText'
import MindmapView from '../components/MindmapView'
import { HiCheckCircle, HiSparkles, HiDocumentText, HiXMark, HiChevronDoubleLeft, HiChevronDoubleRight } from 'react-icons/hi2'

const API_URL = 'http://localhost:3001'

const VIEW_MODES = [
    { id: 'source', icon: '📄', label: 'Source' },
    { id: 'immersive', icon: '📖', label: 'Immersive Text' },
    { id: 'slides', icon: '🎬', label: 'Slides & Narration' },
    { id: 'mindmap', icon: '🧠', label: 'Mindmap' },
]

/* ── Source View: render nội dung gốc từ lesson.content ── */
function SourceView({ content, onActivity }) {
    if (!content) return null
    return (
        <div className="source-view">
            <h2 className="source-title">{content.title}</h2>
            {content.sections?.map((sec, idx) => {
                // Tìm interaction point gắn với section này
                const ip = content.interactionPoints?.find(p => p.sectionIdx === idx)
                return (
                    <div key={idx} className="source-section">
                        <h3 className="source-heading">{sec.heading}</h3>
                        {sec.text && sec.text.split('\n').map((p, i) => (
                            <p key={i} className="source-text">{p}</p>
                        ))}
                        {sec.list && (
                            <ul className="source-list">
                                {sec.list.map((item, i) => <li key={i}>{item}</li>)}
                            </ul>
                        )}
                        {ip && (
                            <button className="source-activity-btn" onClick={() => onActivity(ip)}>
                                <HiSparkles /> Trả lời câu hỏi tương tác
                            </button>
                        )}
                    </div>
                )
            })}
        </div>
    )
}

export default function CourseLearning() {
    const { courseId } = useParams()
    const { lessons } = useContext(AppContext)
    const [activeLesson, setActiveLesson] = useState(null)
    const [activeActivity, setActiveActivity] = useState(null)
    const [uploadedFiles, setUploadedFiles] = useState([])
    const [viewingFile, setViewingFile] = useState(null)
    const [isFullscreen, setIsFullscreen] = useState(false)
    const [activeTab, setActiveTab] = useState('content')
    const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
    const [viewMode, setViewMode] = useState('source')

    const courseData = lessons[courseId]

    // Fetch uploaded files for the current course/lesson
    useEffect(() => {
        if (!courseId) return
        fetchFiles()
    }, [courseId, activeLesson])

    // Reset tab and view when switching lessons
    useEffect(() => {
        setActiveTab('content')
        setViewingFile(null)
        setViewMode('source')
    }, [activeLesson])

    const fetchFiles = async () => {
        try {
            const params = new URLSearchParams({ courseId })
            if (activeLesson && activeLesson !== 'info' && activeLesson !== 'exam') {
                params.set('lessonId', activeLesson)
            }
            const res = await fetch(`${API_URL}/api/uploads?${params.toString()}`)
            if (res.ok) {
                const data = await res.json()
                setUploadedFiles(data)
            }
        } catch (err) {
            console.error('Lỗi tải danh sách tài liệu:', err)
        }
    }

    const formatSize = (bytes) => {
        if (bytes < 1024) return bytes + ' B'
        if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB'
        return (bytes / 1024 / 1024).toFixed(2) + ' MB'
    }

    const getFileIcon = (mimetype) => {
        if (mimetype === 'application/pdf') return '📄'
        if (mimetype?.includes('presentation') || mimetype?.includes('powerpoint')) return '📊'
        if (mimetype?.includes('word')) return '📝'
        return '📎'
    }

    if (!courseData) {
        return (
            <div className="learning-layout">
                <div className="lesson-content-area">
                    <div className="content-placeholder">Khóa học này chưa có dữ liệu demo. Hãy chọn khóa "Học máy" hoặc "Chuyển đổi số".</div>
                </div>
            </div>
        )
    }

    const selectedLesson = courseData.lessons.find(l => l.id === activeLesson)
    const hasContent = selectedLesson?.content
    const isSpecialTab = selectedLesson?.type === 'info' || selectedLesson?.type === 'exam'

    /* ── Render nội dung theo viewMode ── */
    const renderContentByMode = () => {
        const content = selectedLesson.content
        switch (viewMode) {
            case 'source':
                return <SourceView content={content} onActivity={setActiveActivity} />
            case 'immersive':
                return <ImmersiveText courseId={courseId} lessonId={activeLesson} lesson={selectedLesson} />
            case 'mindmap':
                return <MindmapView courseId={courseId} lessonId={activeLesson} lesson={selectedLesson} />
            case 'slides':
                return (
                    <div className="content-placeholder">
                        <div style={{ textAlign: 'center' }}>
                            <span style={{ fontSize: 48, display: 'block', marginBottom: 16 }}>🎬</span>
                            <h3 style={{ margin: '0 0 8px', color: 'var(--text-primary)' }}>Slides & Narration</h3>
                            <p style={{ color: 'var(--text-secondary)', margin: 0, lineHeight: 1.6 }}>
                                Tính năng trình chiếu kèm thuyết minh AI đang được phát triển.<br />
                                Sẽ sớm ra mắt trong phiên bản tiếp theo! 🚀
                            </p>
                        </div>
                    </div>
                )
            default:
                return null
        }
    }

    return (
        <div className="learning-layout" style={{ margin: '-24px', height: 'calc(100% + 48px)' }}>
            {/* Lesson List Sidebar */}
            <div className={`lesson-sidebar ${sidebarCollapsed ? 'collapsed' : ''}`}>
                <button className="lesson-sidebar-toggle" onClick={() => setSidebarCollapsed(!sidebarCollapsed)} title={sidebarCollapsed ? 'Mở danh sách bài' : 'Thu gọn'}>
                    {sidebarCollapsed ? <HiChevronDoubleRight /> : <HiChevronDoubleLeft />}
                </button>
                <div className="lesson-header">
                    {courseData.courseName} ({courseData.courseCode})
                </div>
                {courseData.lessons.map(lesson => {
                    const isExpanded = activeLesson === lesson.id
                    const isSpecial = lesson.type === 'info' || lesson.type === 'exam'
                    return (
                        <div key={lesson.id} className="lesson-item-wrapper">
                            <div
                                className={`lesson-item ${isExpanded ? 'active' : ''}`}
                                onClick={() => setActiveLesson(isExpanded ? null : lesson.id)}
                            >
                                <div style={{ width: 4, minHeight: 28, borderRadius: 2, background: lesson.type === 'exam' ? '#f0ad4e' : 'var(--primary-light)' }} />
                                {!isSpecial && (
                                    <span className={`lesson-toggle ${isExpanded ? 'expanded' : ''}`}>▶</span>
                                )}
                                <span className="lesson-name">{lesson.name}</span>
                                {lesson.completed && <span className="lesson-check"><HiCheckCircle /></span>}
                            </div>
                            {isExpanded && !isSpecial && (
                                <div className="lesson-sub-items">
                                    <div
                                        className={`lesson-sub-item ${activeTab === 'content' ? 'active' : ''}`}
                                        onClick={() => { setActiveTab('content'); setViewingFile(null) }}
                                    >
                                        <span className="sub-bullet">●</span> Nội dung bài học
                                    </div>
                                    <div
                                        className={`lesson-sub-item ${activeTab === 'materials' ? 'active' : ''}`}
                                        onClick={() => setActiveTab('materials')}
                                    >
                                        <span className="sub-bullet">●</span> Tài liệu tham khảo
                                    </div>
                                </div>
                            )}
                        </div>
                    )
                })}
            </div>

            {/* Content Area */}
            <div className="lesson-content-area">
                {!selectedLesson || !hasContent ? (
                    <div className="content-placeholder">
                        {!activeLesson ? 'Vui lòng chọn 1 bài học để hiển thị nội dung.' : 'Nội dung bài học này chưa có dữ liệu demo.'}
                    </div>
                ) : activeTab === 'content' ? (
                    /* === NỘI DUNG BÀI HỌC với View Mode Switcher === */
                    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
                        {/* View Mode Toolbar */}
                        <div className="view-mode-toolbar">
                            {VIEW_MODES.map(mode => (
                                <button
                                    key={mode.id}
                                    className={`view-mode-btn ${viewMode === mode.id ? 'active' : ''}`}
                                    onClick={() => setViewMode(mode.id)}
                                >
                                    <span className="view-mode-icon">{mode.icon}</span>
                                    <span className="view-mode-label">{mode.label}</span>
                                </button>
                            ))}
                        </div>
                        {/* Content by mode */}
                        <div className="view-mode-content">
                            {renderContentByMode()}
                        </div>
                    </div>
                ) : activeTab === 'materials' ? (
                    /* === TÀI LIỆU THAM KHẢO === */
                    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
                        {!viewingFile ? (
                            /* --- File list --- */
                            <>
                                <div style={{ padding: '20px 24px 12px' }}>
                                    <h3 style={{ margin: '0 0 4px', fontSize: 16, color: 'var(--text-primary)' }}>📁 Tài liệu tham khảo</h3>
                                    <p style={{ margin: 0, fontSize: 13, color: 'var(--text-secondary)' }}>Chọn tài liệu bạn muốn xem</p>
                                </div>

                                {uploadedFiles.length === 0 ? (
                                    <div className="content-placeholder" style={{ flex: 1 }}>
                                        Chưa có tài liệu nào được upload cho bài này.<br />
                                        Hãy vào <strong>Upload Tài Liệu</strong> để tải file lên.
                                    </div>
                                ) : (
                                    <div style={{ padding: '0 24px 16px', display: 'flex', flexDirection: 'column', gap: 8 }}>
                                        {uploadedFiles.map((file, idx) => {
                                            const fileUrl = file.downloadUrl
                                                ? `${API_URL}${file.downloadUrl}`
                                                : `${API_URL}/uploads/${file.courseId}/${file.lessonId}/${file.storedName}`
                                            return (
                                                <div
                                                    key={idx}
                                                    onClick={() => { setViewingFile(fileUrl); setIsFullscreen(false) }}
                                                    style={{
                                                        display: 'flex', alignItems: 'center', gap: 12,
                                                        padding: '12px 16px', borderRadius: 10,
                                                        background: 'var(--bg-primary)',
                                                        border: '1px solid var(--border)',
                                                        cursor: 'pointer',
                                                        transition: 'all 0.2s ease',
                                                    }}
                                                >
                                                    <span style={{ fontSize: 28 }}>{getFileIcon(file.mimetype)}</span>
                                                    <div style={{ flex: 1, minWidth: 0 }}>
                                                        <div style={{
                                                            fontWeight: 600, fontSize: 14,
                                                            color: 'var(--text-primary)',
                                                            whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis'
                                                        }}>
                                                            {file.originalName}
                                                        </div>
                                                        <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginTop: 2 }}>
                                                            {formatSize(file.size)}
                                                        </div>
                                                    </div>
                                                    <span style={{ fontSize: 12, color: 'var(--primary)', fontWeight: 500 }}>
                                                        👁 Xem
                                                    </span>
                                                </div>
                                            )
                                        })}
                                    </div>
                                )}
                            </>
                        ) : (
                            /* --- Inline document viewer --- */
                            <div style={{ flex: 1, display: 'flex', flexDirection: 'column', height: '100%' }}>
                                {/* Toolbar */}
                                <div style={{
                                    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                                    padding: '10px 16px',
                                    borderBottom: '1px solid var(--border)',
                                    background: 'var(--bg-secondary)',
                                    flexShrink: 0,
                                }}>
                                    <button
                                        onClick={() => { setViewingFile(null); setIsFullscreen(false) }}
                                        style={{
                                            display: 'flex', alignItems: 'center', gap: 6,
                                            padding: '6px 12px', borderRadius: 6,
                                            border: '1px solid var(--border)', background: 'var(--bg-primary)',
                                            color: 'var(--text-primary)', fontSize: 13,
                                            cursor: 'pointer', fontWeight: 500,
                                        }}
                                    >
                                        ← Quay lại
                                    </button>
                                    <button
                                        onClick={() => setIsFullscreen(true)}
                                        style={{
                                            display: 'flex', alignItems: 'center', gap: 6,
                                            padding: '6px 12px', borderRadius: 6,
                                            border: '1px solid var(--border)', background: 'var(--bg-primary)',
                                            color: 'var(--text-primary)', fontSize: 13,
                                            cursor: 'pointer', fontWeight: 500,
                                        }}
                                        title="Phóng toàn màn hình"
                                    >
                                        ⛶ Toàn màn hình
                                    </button>
                                </div>
                                {/* Iframe */}
                                <iframe
                                    src={`${viewingFile}#view=FitH&toolbar=1`}
                                    style={{ flex: 1, width: '100%', border: 'none', background: '#fff' }}
                                    title="Preview tài liệu"
                                />
                            </div>
                        )}

                        {/* Fullscreen overlay (only when user clicks fullscreen) */}
                        {viewingFile && isFullscreen && (
                            <div style={{
                                position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
                                background: '#fff', zIndex: 9999,
                                display: 'flex', flexDirection: 'column',
                            }}>
                                <div style={{
                                    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                                    padding: '10px 20px',
                                    borderBottom: '1px solid #e0e0e0',
                                    background: '#f8f9fa', flexShrink: 0,
                                }}>
                                    <span style={{ fontSize: 14, fontWeight: 600, color: '#333' }}>
                                        📄 Xem tài liệu
                                    </span>
                                    <button
                                        onClick={() => setIsFullscreen(false)}
                                        style={{
                                            padding: '6px 14px', borderRadius: 6,
                                            border: '1px solid #ccc', background: '#e0e0e0',
                                            color: '#333', fontSize: 13, fontWeight: 500,
                                            cursor: 'pointer',
                                        }}
                                    >
                                        ✕ Thu nhỏ
                                    </button>
                                </div>
                                <iframe
                                    src={viewingFile}
                                    style={{ flex: 1, width: '100%', border: 'none' }}
                                    title="Preview tài liệu"
                                />
                            </div>
                        )}
                    </div>
                ) : null}
            </div>

            {/* Micro Activity Popup */}
            {activeActivity && (
                <MicroActivity activity={activeActivity} onClose={() => setActiveActivity(null)} />
            )}
        </div>
    )
}
